ktor:
  deployment:
    port: 8080
  application:
    modules:
      - xyz.mrjimin.wlink.plugin.SerializationKt.configureSerialization
      - xyz.mrjimin.wlink.di.KoinKt.configureKoin
      - xyz.mrjimin.wlink.plugin.ExposedKt.configureExposed
      - xyz.mrjimin.wlink.plugin.RoutingKt.configureRouting
#      - xyz.mrjimin.wlink.plugin.HttpKt.configureHttp
#      - xyz.mrjimin.wlink.SerializationKt.configureSerialization
#      - xyz.mrjimin.wlink.plugin.SecurityKt.configureSecurity
#      - xyz.mrjimin.wlink.plugin.RequestValidationKt.configureRequestValidation
#      - xyz.mrjimin.wlink.KoinKt.configureKoin
#      - xyz.mrjimin.wlink.RoutingKt.configureRouting
